name = "entwickler"
description = "Hugo theme based on hugo-xmin "
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Gereon Recht"
  homepage = "https://gereonrecht.com"
